export const SHOW_MODEL = "SHOW_MODEL";

export const GET_LIST_BOOKS = "GET_LIST_BOOKS";

export const EDIT_BOOK = "EDIT_BOOK";
export const EDIT_EMPTY_BOOK = "EDIT_EMPTY_BOOK";

export const ADD_BOOKS = "ADD_BOOKS";
export const SET_EDIT_BOOKS = "SET_EDIT_BOOKS";
export const DELETE_BOOKS = "DELETE_BOOKS";

export const UPDATE_QUANTITY_AFTER_CHECKOUT = "UPDATE_QUANTITY_AFTER_CHECKOUT";


export const ADD_DATA_REPORT_BCT = "ADD_DATA_REPORT_BCT";
export const ADD_DATA_REPORT_BCCN = "ADD_DATA_REPORT_BCCN";
