
export const ADD_TO_CART_BS="ADD_TO_CART_BS";
export const UP_TO_CART_BS="UP_TO_CART_BS";
export const DOWN_TO_CART_BS="DOWN_TO_CART_BS";
export const CLEAR_CART_BS="CLEAR_CART_BS";

export const DELETE_TO_CART_BS="DELETE_TO_CART_BS";

export const ADD_CUSTOMER="ADD_CUSTOMER";
export const DELETE_CUSTOMER="DELETE_CUSTOMER";
export const UPDATE_DEBT_CUSTOMER="UPDATE_DEBT_CUSTOMER";